### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/JakartaEELab1#10]
Add unit-tests including tests for endpoints.

**Comment by Charlottehenriksson** [comment]
gh pr checkout 21

**Comment by Charlottehenriksson** [comment]
#21

**Comment by Charlottehenriksson** [comment]
#21 for personRepositoryTest

**Comment by Charlottehenriksson** [comment]
Perhaps this issue is to big/wide and should be split into an issue for each testing part, to have a more clear overview?

**Comment by Win-ther** [comment]
We can add an Issue for the Integration tests and make this Issue only for the Unit-testing if thats better? But adding extra Issues for every test-class, seems a bit unnecessary?

**Comment by Charlottehenriksson** [comment]
https://github.com/Win-ther/JakartaEELab1/pull/19/commits/e0ba59f07e03dec985ef1bce07a377cb715d1361 here is an updated code for pullrequest #19

**Comment by Charlottehenriksson** [comment]
> We can add an Issue for the Integration tests and make this Issue only for the Unit-testing if thats better? But adding extra Issues for every test-class, seems a bit unnecessary?

Yes that sounds good! Im just getting a bit confused :)

**Comment by Win-ther** [comment]
Okay, I will add the Issue. No problem :)

**Comment by Win-ther** [comment]
> > We can add an Issue for the Integration tests and make this Issue only for the Unit-testing if thats better? But adding extra Issues for every test-class, seems a bit unnecessary?
> 
> Yes that sounds good! Im just getting a bit confused :)

If you are confused about anything, we are here to help. Just ask :)

**Comment by Charlottehenriksson** [comment]
https://github.com/Win-ther/JakartaEELab1/pull/24/commits/16e35b43c798616e22db1b92b32a4b20c8009b15 here is updated code for pullrequest #24

**Comment by Charlottehenriksson** [comment]
pull request #25 is updated
