### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/JakartaEELab1#8]
Add dockerfile to easily start application as docker container.

**Comment by Danback** [comment]
Currently working on this.

**Comment by Win-ther** [comment]
> Currently working on this.

Make sure to create a branch here, so we can se that you have started on it.
![image](https://github.com/Win-ther/JakartaEELab1/assets/143023413/1e433d8b-5017-4224-b975-c5afcf3dced7)

**Comment by Danback** [comment]
Sorry got caught up with the other issue yesterday, will look into this one more soon, will create a branch when I do.

**Comment by Win-ther** [comment]
Ofcourse, please hurry a bit though. There is only a week left(where we start with Spring Boot aswell) and this part is integral for the program to work, for us to add the Docker-compose file and for us to start doing IntegrationTests.😊

**Comment by Win-ther** [comment]
> Ofcourse, please hurry a bit though. There is only a week left(where we start with Spring Boot aswell) and this part is integral for the program to work, for us to add the Docker-compose file and for us to start doing IntegrationTests.😊

If you need any help with it, just ask :) I have gotten this part to work in a private test project.

**Comment by Danback** [comment]
@Win-ther I wouldn't mind some help if you've gotten it to work previously!

**Comment by Win-ther** [comment]
Absolutely, contact me on Discord or Teams and I can help you out :)
